/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-07-15 05:26:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.io;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import javax.naming.spi.DirStateFactory.Result;
import java.sql.*;

public final class delete_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("java.time.LocalDate");
    _jspx_imports_classes.add("javax.naming.spi.DirStateFactory.Result");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/WildcatTest/jquery-3.6.0.min.js\"></script>\r\n");

request.setCharacterEncoding("utf-8");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		\r\n");
      out.write("		var now=new Date();\r\n");
      out.write("		var splitYear=now.getFullYear();\r\n");
      out.write("		var splitMonth=(\"0\"+(now.getMonth()+1)).slice(-2);\r\n");
      out.write("		var currentMonth=splitYear+\"-\"+splitMonth;\r\n");
      out.write("		$('#month').val(currentMonth);\r\n");
      out.write("		\r\n");
      out.write("		$('tr').click(function() {\r\n");
      out.write("			var state = confirm(\"정말 삭제하시겠습니까\");\r\n");
      out.write("			if(state){\r\n");
      out.write("				var idx = $(this).find(\"td\").eq(0).text();\r\n");
      out.write("				var id = $(this).find(\"td\").eq(1).text();\r\n");
      out.write("				var subFolderName = $(this).find(\"td\").eq(2).text();\r\n");
      out.write("				location.href = \"/WildcatTest/io/deleteProc.jsp?idx=\" + idx + \"&id=\" + id + \"&subFolderName=\" + subFolderName;	\r\n");
      out.write("			};\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$('#listMonth').click(function(){\r\n");
      out.write("			var i=0;\r\n");
      out.write("			var _month=$('#month').val();\r\n");
      out.write("			var mArray = _month.split(\"-\");\r\n");
      out.write("			var selectMonth = mArray[0] + \"-\" + mArray[1];\r\n");
      out.write("			var idxMonth=mArray[0]+mArray[1];			\r\n");
      out.write("			var url=\"deleteMonth.jsp?selectMonth=\" + selectMonth + \"&idxMonth=\" + idxMonth;\r\n");
      out.write("			location.href=url;\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("a {\r\n");
      out.write("	color: black;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("#tBody:hover {\r\n");
      out.write("	color: white;\r\n");
      out.write("	background-color: gray;\r\n");
      out.write("}\r\n");
      out.write(".idxHidden>*:first-child {\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

	Class.forName("oracle.jdbc.driver.OracleDriver");
	Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "rysdne", "3882");

	String sql = "select * from WildcatTest where id=? order by idx desc";
	PreparedStatement pstmt = conn.prepareStatement(sql);
	pstmt.setString(1, (String)session.getAttribute("id"));
	ResultSet rs = pstmt.executeQuery();
	
      out.write("\r\n");
      out.write("	<div>\r\n");
      out.write("	<input type=\"month\" id=\"month\" name=\"month\">\r\n");
      out.write("	<input type=\"button\" id=\"listMonth\" value=\"검색\">\r\n");
      out.write("	<button onclick=\"location.href='delete.jsp'\">초기화</button>\r\n");
      out.write("	<button onclick='location.href=\"/WildcatTest/login/logout.jsp\"'>로그아웃</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	<table border=\"1\">\r\n");
      out.write("		<tr class=\"idxHidden\">\r\n");
      out.write("			<th>idx</th>\r\n");
      out.write("			<th>계정</th>\r\n");
      out.write("			<th>폴더</th>\r\n");
      out.write("			<th>타이틀</th>\r\n");
      out.write("			<th>생성일</th>\r\n");
      out.write("			<th>생성시간</th>\r\n");
      out.write("		</tr>\r\n");
      out.write("		");

		while (rs.next()) {
		
      out.write("\r\n");
      out.write("		<tr id=\"tBody\" class=\"idxHidden\">\r\n");
      out.write("			<td>");
      out.print(rs.getLong("idx"));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString("id"));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString("subfolder"));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString("title"));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString("cdate"));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print(rs.getString("ctime"));
      out.write("</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		");

		}
		
		pstmt.close();
		conn.close();
		
		
      out.write("\r\n");
      out.write("	</table>\r\n");
      out.write("	<button onclick=\"location.href='/WildcatTest/index.jsp'\">메인 메뉴</button>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
